CREATE DATABASE QL_QuanKara;
GO

USE QL_QuanKara;
GO

CREATE TABLE dbo.ROOM(
	ID_ROOM VARCHAR(10),
	ROOM_NAME NVARCHAR(20),
	ROOM_TYPE NVARCHAR(20) NOT NULL,
	PRICE	BIGINT NOT NULL DEFAULT 0,
	CAPACITY INT,

	CONSTRAINT PK_ROOM PRIMARY KEY(ID_ROOM)
)
GO

CREATE TABLE dbo.EMPLOYEE(
	ID_EMPLOYEE INT IDENTITY(1,1) NOT NULL,
	NAME NVARCHAR(99) NOT NULL,
	PHONE CHAR(15),
	EMAIL VARCHAR(99),
	ID_CARD VARCHAR(20) NOT NULL,
	ADDRESS NVARCHAR(99) NOT NULL,
	ROLE_EMOLOYEE NVARCHAR(20) NOT NULL,
	DoB DATE NOT NULL,
	ACCOUNT_NAME VARCHAR(20),

	CONSTRAINT PK_EMPLOYEE PRIMARY KEY(ID_EMPLOYEE),
	CONSTRAINT FK_EMPLOYEE FOREIGN KEY(ACCOUNT_NAME) REFERENCES ACCOUNT(ACCOUNT_NAME)
);
GO

CREATE TABLE dbo.ACCOUNT(
	ACCOUNT_NAME VARCHAR(20),
	PASSWORD VARCHAR(40),
	ROLE VARCHAR(20)

	CONSTRAINT FK_ACCOUNT PRIMARY KEY(ACCOUNT_NAME)
);
GO


CREATE TABLE dbo.MENU(
	ID INT IDENTITY(1,1) NOT NULL,
	NAME NVARCHAR(50) NOT NULL,
	PRICE BIGINT NOT NULL

	CONSTRAINT PK_MENU PRIMARY KEY(ID)
)
GO

CREATE TABLE dbo.ORDER_S(
	ID_ORDER INT IDENTITY(1,1) NOT NULL,
	ID_ROOM_ORDER INT NOT NULL ,
	ID_MENU INT ,
	QTY INT  DEFAULT 0 ,
	NOTE NVARCHAR(99),
	TOTAL_PRICE BIGINT,

	CONSTRAINT PK_ORDER_ PRIMARY KEY(ID_ORDER),
	CONSTRAINT FK_ORDER_ROOM_ORDER FOREIGN KEY(ID_ROOM_ORDER) REFERENCES ROOM_ORDER(ID_ROOM_ORDER), 
	CONSTRAINT FK_ORDER_MENU FOREIGN KEY(ID_MENU) REFERENCES MENU(ID),
)
GO


CREATE TABLE dbo.CUSTOMER(
	ID_CUSTOMER INT IDENTITY(1,1) NOT NULL,
	CUSTOMER_NAME NVARCHAR(99) NOT NULL,
	PHONE CHAR(15),
	EMAIL VARCHAR(99),
	ID_CARD VARCHAR(20),

	CONSTRAINT PK_CUSTOMER PRIMARY KEY(ID_CUSTOMER)
)
GO

CREATE TABLE dbo.ROOM_ORDER(
	ID_ROOM_ORDER INT IDENTITY(1,1) NOT NULL,
	ID_ROOM VARCHAR(10) NOT NULL,
	ID_CUSTOMER INT NOT NULL,
	TIME_IN TIME NOT NULL,
	TIME_OUT TIME,

	CONSTRAINT PK_ROOM_ORDER PRIMARY KEY(ID_ROOM_ORDER),
	CONSTRAINT FK_ROOM_ORDER_ROOM FOREIGN KEY(ID_ROOM) REFERENCES ROOM(ID_ROOM),
	CONSTRAINT FK_ROOM_ORDER_CUSTOMER FOREIGN KEY(ID_CUSTOMER) REFERENCES CUSTOMER(ID_CUSTOMER),
);
GO

CREATE TABLE dbo.BILL(
	ID_BILL INT IDENTITY(1,1) NOT NULL,
	ID_ROOM_ORDER INT NOT NULL,
	ID_EMPLOYEE INT NOT NULL,
	TOTAL BIGINT,
	TAX INT,
	STATUS NVARCHAR(40) NOT NULL ,

	CONSTRAINT PK_BILL PRIMARY KEY(ID_BILL),
	CONSTRAINT FK_BILL_ROOM_ORDER FOREIGN KEY(ID_ROOM_ORDER) REFERENCES ROOM_ORDER(ID_ROOM_ORDER),
	CONSTRAINT FK_BILL_EMPLOYEE FOREIGN KEY(ID_EMPLOYEE) REFERENCES EMPLOYEE(ID_EMPLOYEE),
);
GO





